<?php

return "
-- Users
CREATE TABLE IF NOT EXISTS users (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   username TEXT NOT NULL UNIQUE,
   password_hash TEXT NOT NULL,  -- bcrypt
   email TEXT,
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Sessions (for authorization)
CREATE TABLE IF NOT EXISTS sessions (
   token TEXT PRIMARY KEY,
   user_id INTEGER NOT NULL,
   expires_at DATETIME NOT NULL,
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Folders
CREATE TABLE IF NOT EXISTS folders (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   user_id INTEGER NOT NULL,
   parent_id INTEGER,              -- NULL = root level
   name TEXT NOT NULL,
   icon TEXT DEFAULT '📁',          -- emoji
   position INTEGER DEFAULT 0,     -- Sorting
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (user_id) REFERENCES users(id),
   FOREIGN KEY (parent_id) REFERENCES folders(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_folders_user ON folders(user_id, parent_id);

-- Notes
CREATE TABLE IF NOT EXISTS notes (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   user_id INTEGER NOT NULL,
   folder_id INTEGER,
   title TEXT NOT NULL,
   content TEXT NOT NULL,          -- Markdown/HTML
   preview TEXT,                   -- First 200 chars for list view
   is_pinned INTEGER DEFAULT 0,    -- Pinned note
   is_archived INTEGER DEFAULT 0,  -- Archived note
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (user_id) REFERENCES users(id),
   FOREIGN KEY (folder_id) REFERENCES folders(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_notes_user_folder ON notes(user_id, folder_id);
CREATE INDEX IF NOT EXISTS idx_notes_pinned ON notes(user_id, is_pinned, updated_at);

-- Full-text search index (FTS5)
CREATE VIRTUAL TABLE IF NOT EXISTS notes_fts USING fts5(
   title,
   content,
   content='notes',
   content_rowid='id'
);

-- Triggers for auto-updating FTS
CREATE TRIGGER IF NOT EXISTS notes_after_insert AFTER INSERT ON notes BEGIN
   INSERT INTO notes_fts(rowid, title, content)
    VALUES (new.id, new.title, new.content);
END;

CREATE TRIGGER IF NOT EXISTS notes_after_update AFTER UPDATE ON notes BEGIN
   UPDATE notes_fts SET title=new.title, content=new.content
    WHERE rowid=old.id;
END;

CREATE TRIGGER IF NOT EXISTS notes_after_delete AFTER DELETE ON notes BEGIN
   DELETE FROM notes_fts WHERE rowid=old.id;
END;

-- Tags
CREATE TABLE IF NOT EXISTS tags (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   name TEXT NOT NULL UNIQUE,
   color TEXT DEFAULT '#3B82F6'   -- Generated by hash
);

-- Note-Tags link (many-to-many)
CREATE TABLE IF NOT EXISTS note_tags (
   note_id INTEGER NOT NULL,
   tag_id INTEGER NOT NULL,
   PRIMARY KEY (note_id, tag_id),
   FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE,
   FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_note_tags_tag ON note_tags(tag_id);

-- Files (images + documents)
CREATE TABLE IF NOT EXISTS files (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   note_id INTEGER NOT NULL,
   user_id INTEGER NOT NULL,
   type TEXT NOT NULL,             -- 'image', 'pdf', 'docx', 'zip', etc
   filename TEXT NOT NULL,         -- Original name
   stored_name TEXT NOT NULL,      -- UUID.ext on disk
   size INTEGER NOT NULL,          -- Size in bytes
   mime_type TEXT NOT NULL,
   uploaded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE,
   FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_files_note ON files(note_id);
";
